theme: jekyll-theme-minimal
title: Francisco Roldán
description: PhD Candidate | Economics
logo: ![.](https://lh4.googleusercontent.com/aOPotfmxKmDROeMPtd1BlscgW1cjw8vA8Lb0dL2y5yaYwUgkX6bAgVCBNSstczFAvcS4s9D46jGZLP3D-JbUtXsntGTtscsY248BIClxqeluZ3D50LE=w271)
